import { requirePage,ApiError } from '@/lib/server/auth';import {check} from '@/lib/server/data';

async function total(query:PromiseLike<{error:{message:string}|null;count:number|null}>){const result=await query;if(result.error)throw new ApiError(503,'DATABASE_ERROR','Administrative metrics are temporarily unavailable.');return result.count??0;}

export default async function Page(){
 const {db,profile}=await requirePage(true);
 const pending=profile.role==='SUPER_ADMIN'?total(db.from('admin_role_requests').select('id',{count:'exact',head:true}).eq('status','PENDING')):Promise.resolve<number|null>(null);
 const metrics=await Promise.all([
  total(db.from('profiles').select('id',{count:'exact',head:true})),total(db.from('profiles').select('id',{count:'exact',head:true}).eq('role','STUDENT')),total(db.from('profiles').select('id',{count:'exact',head:true}).in('role',['ADMIN','SUPER_ADMIN'])),pending,
  total(db.from('questions').select('id',{count:'exact',head:true}).eq('publication_status','PUBLISHED')),total(db.from('questions').select('id',{count:'exact',head:true}).in('lifecycle',['STAGED','PENDING_REVIEW','VALIDATION_REQUIRED'])),
  total(db.from('contributions').select('id',{count:'exact',head:true})),total(db.from('contributions').select('id',{count:'exact',head:true}).eq('review_state','PENDING')),total(db.from('processing_jobs').select('id',{count:'exact',head:true}).in('status',['FAILED','DEAD_LETTER','NEEDS_REVIEW'])),
  total(db.from('comment_reports').select('id',{count:'exact',head:true}).eq('status','OPEN')),total(db.from('external_sources').select('id',{count:'exact',head:true}).eq('enabled',true)),total(db.from('ingestion_runs').select('id',{count:'exact',head:true})),total(db.from('attempts').select('id',{count:'exact',head:true}).eq('status','COMPLETED')),
 ]);
 const labels=['Total users','Students','Admins','Pending admin approvals','Published questions','Staged / pending questions','Contributions','Contributions awaiting review','Failed / review jobs','Pending reports','Active external sources','Ingestion runs','Completed tests'];
 const [activity,subjects,questions,jobs,runs]=await Promise.all([db.from('audit_events').select('id,action,target_type,target_id,created_at').order('created_at',{ascending:false}).limit(8),db.from('subjects').select('id,name').order('name'),db.from('questions').select('subject_id,lifecycle,verification_status,publication_status'),db.from('processing_jobs').select('status'),db.from('ingestion_runs').select('status,started_at,finished_at,error').order('started_at',{ascending:false}).limit(1)]);check(activity);check(subjects);check(questions);check(jobs);check(runs);
 const questionRows=questions.data??[],jobRows=jobs.data??[],lastRun=runs.data?.[0];
 return <><p className="eyebrow">Role-authorized administration</p><h1>Admin Dashboard</h1><p>Live operational totals and queue health from PostgreSQL. No fixture numbers are used.</p><div className="stats admin-stats">{labels.map((label,index)=>metrics[index]===null?null:<section className="card" key={label}><p>{label}</p><div className="metric">{metrics[index]}</div></section>)}</div><div className="admin-grid"><section className="card"><h2>Attention required</h2><div className="health-list"><div className="health-row"><span>Question review queue</span><strong>{metrics[5]}</strong></div><div className="health-row"><span>Contribution review</span><strong>{metrics[7]}</strong></div><div className="health-row"><span>Failed / manual jobs</span><strong>{metrics[8]}</strong></div><div className="health-row"><span>Open reports</span><strong>{metrics[9]}</strong></div></div></section><section className="card"><h2>Processing health</h2><div className="health-list">{['READY','RUNNING','RETRY','SUCCEEDED','FAILED','NEEDS_REVIEW'].map(status=><div className="health-row" key={status}><span>{status.replaceAll('_',' ')}</span><strong>{jobRows.filter(j=>j.status===status).length}</strong></div>)}</div><p className="muted">Last ingestion: {lastRun?`${lastRun.status} · ${new Date(lastRun.started_at).toLocaleString()}`:'No runs yet'}</p></section><section className="card"><h2>Question bank health</h2>{(subjects.data??[]).map(subject=>{const rows=questionRows.filter(q=>q.subject_id===subject.id),published=rows.filter(q=>q.publication_status==='PUBLISHED').length;return <div className="health-row" key={subject.id}><span>{subject.name}</span><strong>{published} published / {rows.length} total</strong></div>})}</section></div><section className="card section"><h2>Recent activity</h2>{(activity.data??[]).map(event=><div className="health-row" key={event.id}><span><strong>{event.action.replaceAll('_',' ')}</strong> · {event.target_type}</span><time>{new Date(event.created_at).toLocaleString()}</time></div>)}{!activity.data?.length&&<p className="muted">No administrative activity recorded yet.</p>}</section></>;
}
