'use client';
import { useState } from 'react';
import { api } from '@/lib/client-api';
type Comment={id:string;user_id:string;body:string;parent_id:string|null;status:string;created_at:string};
export function Community({initial,userId,staff=false}:{initial:Comment[];userId:string;staff?:boolean}){
 const [comments,setComments]=useState(initial);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const [reply,setReply]=useState<string|null>(null);const [report,setReport]=useState<string|null>(null);const [page,setPage]=useState(0);
 async function action(path:string,body:unknown){setBusy(true);setMessage('');try{await api(path,'POST',body);setComments(await api<Comment[]>('comments'));setReply(null);setReport(null);setMessage('Saved.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 return <><form className="card form" onSubmit={e=>{e.preventDefault();const f=e.currentTarget;void action('comments',{body:new FormData(f).get('body'),parent_id:reply,question_id:null}).then(()=>f.reset());}}><label>{reply?'Write a reply':'Start a study discussion'}<textarea name="body" maxLength={4000} required/></label><div className="toolbar"><button className="button" disabled={busy}>Post</button>{reply&&<button className="button secondary" type="button" onClick={()=>setReply(null)}>Cancel reply</button>}</div></form><p role="status">{message}</p>{comments.filter(c=>c.parent_id===null).map(c=><article className="card section" key={c.id}><p className="muted">{c.user_id===userId?'You':'Community member'} · {new Date(c.created_at).toLocaleDateString()} · {c.status.toLowerCase()}</p><p className="question-text">{c.body}</p><div className="toolbar"><button className="button secondary" disabled={busy} onClick={()=>setReply(c.id)}>Reply</button><button className="button secondary" disabled={busy} onClick={()=>void action(`comments/${c.id}/reaction`,{reaction:'HELPFUL'})}>Helpful</button><button className="button secondary" onClick={()=>setReport(c.id)}>Report</button>{(c.user_id===userId||staff)&&<button className="button secondary" disabled={busy} onClick={()=>void action(`comments/${c.id}/moderate`,{action:staff?'HIDE':'DELETE'})}>{staff?'Hide':'Delete'}</button>}</div>{report===c.id&&<form className="form section" onSubmit={e=>{e.preventDefault();void action(`comments/${c.id}/report`,{reason:new FormData(e.currentTarget).get('reason')});}}><label>Reason for reporting<textarea name="reason" minLength={3} maxLength={1000} required/></label><button className="button" disabled={busy}>Submit report</button></form>}{comments.filter(r=>r.parent_id===c.id).map(r=><blockquote key={r.id}><p>{r.body}</p><small>Reply · {new Date(r.created_at).toLocaleDateString()}</small></blockquote>)}</article>)}{comments.length===0&&<p className="card section">No discussions yet. Ask a study question to begin.</p>}<div className="toolbar"><button className="button secondary" disabled={page===0||busy} onClick={()=>{const n=page-1;void api<Comment[]>(`comments?page=${n}`).then(r=>{setComments(r);setPage(n);}).catch(e=>setMessage(e.message));}}>Previous</button><button className="button secondary" disabled={comments.length<50||busy} onClick={()=>{const n=page+1;void api<Comment[]>(`comments?page=${n}`).then(r=>{setComments(r);setPage(n);}).catch(e=>setMessage(e.message));}}>Next</button></div></>;
}
