'use client';
import { useState } from 'react';
import { api } from '@/lib/client-api';
export type Flashcard={id:string;front:string;back:string;due:string;revision:number;state:Record<string,unknown>};
export function Flashcards({initial,counts}:{initial:Flashcard[];counts:{due:number;new:number;learning:number;review:number}}){
 const [cards,setCards]=useState(initial);const [revealed,setRevealed]=useState(false);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [reviewed,setReviewed]=useState(0);const card=cards[0];
 async function rate(rating:number){if(!card)return;setBusy(true);try{await api(`flashcards/${card.id}/review`,'POST',{rating,request_key:crypto.randomUUID()});setCards(await api<Flashcard[]>('flashcards'));setReviewed(n=>n+1);setRevealed(false);setMessage('Review saved. Your next due date has been scheduled.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 return <><div className="stats">{[['Due today',counts.due],['New',counts.new],['Learning',counts.learning],['Review',counts.review]].map(([label,value])=><section className="card" key={label}><span className="muted">{label}</span><div className="metric">{value}</div></section>)}</div>{message&&<p role="status">{message}</p>}{!card?<section className="card empty-state"><h2>{reviewed?`Session complete — ${reviewed} cards reviewed`:'No cards are due'}</h2><p>{reviewed?'Your FSRS due dates were updated after every rating.':'Add flashcards from completed question reviews.'}</p></section>:<section className="card"><p className="eyebrow">{cards.length} due in this batch · {reviewed} completed</p><div className="game-progress"><i style={{width:`${100*reviewed/Math.max(1,initial.length)}%`}}/></div><h2>{card.front}</h2>{revealed?<><p className="question-text">{card.back}</p><div className="toolbar">{['Again','Hard','Good','Easy'].map((label,i)=><button key={label} className="button" disabled={busy} onClick={()=>void rate(i+1)}>{label}</button>)}</div></>:<button className="button" onClick={()=>setRevealed(true)}>Reveal answer</button>}</section>}</>;
}
