'use client';
import {useEffect,useMemo,useState} from 'react';import {api} from '@/lib/client-api';
type Mode='RAPID_FIRE'|'RAPID_RECALL'|'MISTAKE_RESCUE'|'ACCURACY'|'DAILY_CHALLENGE';
type Item={question_id:string;position:number;snapshot:{question_text:string;option_a:string;option_b:string;option_c:string;option_d:string;difficulty:string;topic_id:string|null}};
type Session={id:string;mode:Mode;question_count:number;items:Item[]};
type Result={correct:boolean;correct_answer:string;explanation:string;completed:boolean;completed_count:number;correct_count:number};
const modes:{mode:Mode;title:string;purpose:string;count:number;premium?:boolean}[]=[
 {mode:'RAPID_FIRE',title:'Rapid Fire',purpose:'Fast retrieval with an accuracy-first combo. You have 20 seconds per item.',count:10},
 {mode:'RAPID_RECALL',title:'Rapid Recall',purpose:'Recall first, reveal choices, then rate how well you knew it.',count:8},
 {mode:'MISTAKE_RESCUE',title:'Mistake Rescue',purpose:'Revisit questions you previously missed and repair the concept.',count:8,premium:true},
 {mode:'ACCURACY',title:'Accuracy Mode',purpose:'Untimed, low-pressure practice focused on careful correctness.',count:10},
 {mode:'DAILY_CHALLENGE',title:'Daily Challenge',purpose:'A short verified question mix that records today’s learning activity.',count:10,premium:true},
];
export function InteractiveGames({history,tier}:{history:Array<{id:string;mode:string;status:string;correct_count:number;question_count:number;started_at:string}>;tier:'FREE'|'PREMIUM'}){
 const [session,setSession]=useState<Session|null>(null),[index,setIndex]=useState(0),[selected,setSelected]=useState(''),[result,setResult]=useState<Result|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[revealed,setRevealed]=useState(false),[rating,setRating]=useState<'KNEW_IT'|'ALMOST'|'DIDNT_KNOW'|null>(null),[started,setStarted]=useState(0),[seconds,setSeconds]=useState(20);
 const item=session?.items[index];const timed=session?.mode==='RAPID_FIRE';
 useEffect(()=>{if(!timed||!item||result)return;const timer=setInterval(()=>setSeconds(s=>Math.max(0,s-1)),1000);return()=>clearInterval(timer)},[timed,item,result]);
 const combo=useMemo(()=>result?.correct?result.correct_count:0,[result]);
 async function start(mode:Mode,count:number,eventTime:number){setBusy(true);setMessage('');try{const data=await api<Session>('learning-games','POST',{mode,count});setSession(data);setIndex(0);setSelected('');setResult(null);setRevealed(mode!=='RAPID_RECALL');setRating(null);setSeconds(20);setStarted(eventTime);}catch(error){setMessage((error as Error).message);}finally{setBusy(false)}}
 async function answer(eventTime:number){if(!session||!item||!selected)return;setBusy(true);try{const data=await api<Result>(`learning-games/${session.id}/answer`,'POST',{question_id:item.question_id,answer:selected,rating,response_ms:Math.max(0,Math.round(eventTime-started))});setResult(data);}catch(error){setMessage((error as Error).message);}finally{setBusy(false)}}
 function next(eventTime:number){if(!session)return;if(index+1>=session.items.length){setSession(null);setMessage(`Session complete. ${result?.correct_count??0} of ${session.question_count} correct; the result was saved separately from official tests.`);return}setIndex(i=>i+1);setSelected('');setResult(null);setRating(null);setRevealed(session.mode!=='RAPID_RECALL');setSeconds(20);setStarted(eventTime)}
 if(session&&item)return <section className="game-stage card"><div className="top"><div><p className="eyebrow">{modes.find(m=>m.mode===session.mode)?.title}</p><h1>{index+1} / {session.question_count}</h1></div>{timed&&<div className="timer" aria-live="polite">{seconds}s</div>}</div><div className="game-progress"><i style={{width:`${100*(index+(result?1:0))/session.question_count}%`}}/></div><h2>{item.snapshot.question_text}</h2>{session.mode==='RAPID_RECALL'&&!revealed?<button className="button" onClick={()=>setRevealed(true)}>Reveal answer choices</button>:<fieldset className="options" disabled={!!result}>{(['A','B','C','D'] as const).map(key=><label className={`option ${selected===key?'selected':''}`} key={key}><input type="radio" name="game-answer" value={key} checked={selected===key} onChange={()=>setSelected(key)}/><strong>{key}</strong> {item.snapshot[`option_${key.toLowerCase()}` as 'option_a']}</label>)}</fieldset>}{session.mode==='RAPID_RECALL'&&revealed&&!result&&<div className="toolbar" aria-label="Recall confidence">{([['KNEW_IT','Knew it'],['ALMOST','Almost'],['DIDNT_KNOW',"Didn't know"]] as const).map(([value,label])=><button type="button" className={`button ${rating===value?'':'secondary'}`} key={value} onClick={()=>setRating(value)}>{label}</button>)}</div>}{!result&&revealed&&<button className="button section" disabled={!selected||busy||(session.mode==='RAPID_RECALL'&&!rating)} onClick={event=>void answer(event.timeStamp)}>{busy?'Checking…':'Check answer'}</button>}{result&&<section className={result.correct?'success section':'error section'}><h2>{result.correct?'Correct':'Not yet'}</h2><p>Correct answer: {result.correct_answer}. {result.explanation}</p><p>{timed&&result.correct?`Accuracy combo: ${combo}`:'This learning-game result does not change an official MEC test score.'}</p><button className="button" onClick={event=>next(event.timeStamp)}>{result.completed?'Finish session':'Next'}</button></section>}</section>;
 return <><p className="eyebrow">Interactive retrieval practice · {tier}</p><h1>Learning games</h1><p>Each mode uses verified, published question-bank content and persists outcomes separately from official exam attempts.</p><div className="game-grid">{modes.map(m=>{const locked=!!m.premium&&tier!=='PREMIUM';return <article className="card game-card" key={m.mode}><span className="pill">{m.count} items{m.premium?' · Premium':''}</span><h2>{m.title}</h2><p>{m.purpose}</p><button className="button" disabled={busy||locked} onClick={event=>void start(m.mode,m.count,event.timeStamp)}>{locked?'Premium required':`Start ${m.title}`}</button></article>})}</div><p role="status" className={message.includes('complete')?'success':message?'error':''}>{message}</p><section className="card section"><h2>Recent game sessions</h2>{history.length?<div className="table-wrap"><table><thead><tr><th>Mode</th><th>Result</th><th>Status</th><th>Date</th></tr></thead><tbody>{history.map(h=><tr key={h.id}><td>{h.mode.replaceAll('_',' ')}</td><td>{h.correct_count} / {h.question_count}</td><td>{h.status}</td><td>{new Date(h.started_at).toLocaleDateString()}</td></tr>)}</tbody></table></div>:<p className="muted">Complete a mode to begin your retrieval-practice history.</p>}</section></>;
}
