'use client';
import { useState } from 'react';
import { api } from '@/lib/client-api';
type Entry={id:string;display_name:string;xp:number;rank:number;tests_completed:number;questions_answered:number;accuracy:number|null;average_score:number|null;best_score:number|null;streak:number;target_score:number|null;recent_trend:number};
type Ranking={full_access:boolean;viewer_id:string;entries:Entry[]};
export function Leaderboard({initial,optIn}:{initial:Ranking;optIn:boolean}){
 const [data,setData]=useState(initial);const [opt,setOpt]=useState(optIn);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
 async function change(value:boolean){setBusy(true);try{await api('leaderboard','PATCH',{opt_in:value});setData(await api<Ranking>('leaderboard'));setOpt(value);}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 const others=data.entries.filter(e=>e.id!==data.viewer_id);
 return <><label className="check-label"><input type="checkbox" checked={opt} disabled={busy} onChange={e=>void change(e.target.checked)}/>Share my leaderboard progress with other learners</label><p className="muted">Only learners who choose to share appear with identifiable progress. Individual answers and private test history are never shared.</p>{!data.full_access&&<p className="card section">Free access shows your own summary. Comparing opted-in learners requires an active full-leaderboard entitlement.</p>}{data.full_access&&others.length===0?<p className="card section">Only you are currently sharing leaderboard progress. Other learners appear when they opt in.</p>:null}<p role="status">{message}</p><div className="card table-wrap leaderboard-table"><table><thead><tr><th>Rank</th><th>Learner</th><th>XP</th><th>Tests</th><th>Answered</th><th>Accuracy</th><th>Average</th><th>Best</th><th>Streak</th><th>Progress</th></tr></thead><tbody>{data.entries.map(e=><tr key={e.id} className={e.id===data.viewer_id?'leaderboard-own-row':undefined}><td>#{e.rank}</td><td>{e.display_name}</td><td>{e.xp}</td><td>{e.tests_completed}</td><td>{e.questions_answered}</td><td>{e.accuracy===null?'—':`${e.accuracy.toFixed(1)}%`}</td><td>{e.average_score===null?'—':`${e.average_score.toFixed(1)}%`}</td><td>{e.best_score===null?'—':`${e.best_score.toFixed(1)}%`}</td><td>{e.streak} days</td><td>{e.recent_trend>0?`↑ ${e.recent_trend.toFixed(1)}%`:e.recent_trend<0?`↓ ${Math.abs(e.recent_trend).toFixed(1)}%`:'—'}</td></tr>)}</tbody></table></div></>;
}
