'use client';
import { useState } from 'react';
import { api } from '@/lib/client-api';
type Entry={id:string;display_name:string;xp?:number|null;rank?:number|null;tests_completed?:number|null;questions_answered?:number|null;accuracy?:number|null;average_score?:number|null;best_score?:number|null;streak?:number|null;target_score?:number|null;recent_trend?:number|null};
type Ranking={full_access:boolean;viewer_id:string;entries:Entry[]};
function numeric(value:unknown){return typeof value==='number'&&Number.isFinite(value)?value:null;}
function whole(value:unknown){return numeric(value)===null?0:Math.round(numeric(value)!);}
function percent(value:unknown){const n=numeric(value);return n===null?'—':`${n.toFixed(1)}%`;}
export function Leaderboard({initial,optIn}:{initial:Ranking;optIn:boolean}){
 const [data,setData]=useState(initial);const [opt,setOpt]=useState(optIn);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
 async function change(value:boolean){setBusy(true);try{await api('leaderboard','PATCH',{opt_in:value});setData(await api<Ranking>('leaderboard'));setOpt(value);}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 const others=data.entries.filter(e=>e.id!==data.viewer_id);
 return <><label className="check-label"><input type="checkbox" checked={opt} disabled={busy} onChange={e=>void change(e.target.checked)}/>Share my leaderboard progress with other learners</label><p className="muted">Only learners who choose to share appear with identifiable progress. Individual answers and private test history are never shared.</p>{!data.full_access&&<p className="card section">Free access shows your own summary. Comparing opted-in learners requires an active full-leaderboard entitlement.</p>}{data.full_access&&others.length===0?<p className="card section">Only you are currently sharing leaderboard progress. Other learners appear when they opt in.</p>:null}<p role="status">{message}</p><div className="card table-wrap leaderboard-table"><table><thead><tr><th>Rank</th><th>Learner</th><th>XP</th><th>Tests</th><th>Answered</th><th>Accuracy</th><th>Average</th><th>Best</th><th>Streak</th><th>Target</th><th>Progress</th></tr></thead><tbody>{data.entries.map(e=>{const trend=numeric(e.recent_trend);return <tr key={e.id} className={e.id===data.viewer_id?'leaderboard-own-row':undefined}><td>#{whole(e.rank)}</td><td>{e.display_name||'Learner'}</td><td>{whole(e.xp)}</td><td>{whole(e.tests_completed)}</td><td>{whole(e.questions_answered)}</td><td>{percent(e.accuracy)}</td><td>{percent(e.average_score)}</td><td>{percent(e.best_score)}</td><td>{whole(e.streak)} days</td><td>{numeric(e.target_score)===null?'—':numeric(e.target_score)}</td><td>{trend===null||trend===0?'—':trend>0?`↑ ${trend.toFixed(1)}%`:`↓ ${Math.abs(trend).toFixed(1)}%`}</td></tr>})}</tbody></table></div></>;
}
