'use client';
import { useState } from 'react';
import { api } from '@/lib/client-api';
import type { AttemptDetail } from '@/lib/contracts';
export function Review({detail,saved}:{detail:AttemptDetail;saved:string[]}){
 const [filter,setFilter]=useState('ALL');const [bookmarks,setBookmarks]=useState(new Set(saved));const [error,setError]=useState('');const [busy,setBusy]=useState('');
 async function bookmark(id:string){setBusy(id);try{const state=await api<boolean>('bookmarks','POST',{question_id:id,saved:!bookmarks.has(id)});setBookmarks(prev=>{const next=new Set(prev);if(state)next.add(id);else next.delete(id);return next;});}catch(e){setError((e as Error).message);}finally{setBusy('');}}
 return <section><div className="top"><h2>Detailed answer review</h2><label>Show<select value={filter} onChange={e=>setFilter(e.target.value)}>{['ALL','CORRECT','INCORRECT','UNANSWERED','MARKED'].map(v=><option key={v}>{v}</option>)}</select></label></div>{error&&<p role="alert" className="error">{error}</p>}{detail.questions.filter(q=>filter==='ALL'||filter==='CORRECT'&&q.is_correct||filter==='INCORRECT'&&q.is_correct===false||filter==='UNANSWERED'&&q.selected_answer===null||filter==='MARKED'&&q.marked_for_review).map(q=><article className="card section" key={q.question_id}><div className="top"><span className="badge">Question {q.position} · {q.selected_answer==null?'Unanswered':q.is_correct?'Correct':'Incorrect'} · {q.awarded_marks} marks</span><button className="button secondary" disabled={busy===q.question_id} onClick={()=>void bookmark(q.question_id)}>{bookmarks.has(q.question_id)?'Remove bookmark':'Bookmark'}</button></div><button className="button secondary section" disabled={busy===q.question_id} onClick={async()=>{setBusy(q.question_id);try{await api("flashcards","POST",{question_id:q.question_id});setError("Flashcard added.");}catch(e){setError((e as Error).message);}finally{setBusy("");}}}>Add flashcard</button><h3>{q.snapshot.question_text}</h3><p>Your answer: {q.selected_answer??'—'} · Correct answer: <strong>{q.correct_answer}</strong></p><div className="review-options">{(['A','B','C','D'] as const).map(k=><p key={k}><strong>{k}. {q.snapshot[`option_${k.toLowerCase()}` as 'option_a']}</strong><br/>{q.option_explanations?.[k]}</p>)}</div><p>{q.explanation}</p><details><summary>Question details and source</summary><p>{q.snapshot.difficulty} · {q.snapshot.cognitive_level} · {Math.round((q.response_ms??0)/1000)} seconds recorded</p><pre>{JSON.stringify(q.provenance,null,2)}</pre></details></article>)}</section>;
}
