'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import type { Route } from 'next';
import { api } from '@/lib/client-api';
import type { Taxonomy } from '@/lib/contracts';
export function TestPicker({taxonomy:t,preferred}:{taxonomy:Taxonomy;preferred:string|null}){
 const router=useRouter();const [program,setProgram]=useState(preferred??'');const [mode,setMode]=useState('FULL');const [subject,setSubject]=useState('');const [topic,setTopic]=useState('');const [count,setCount]=useState(10);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const group=t.programs.find(p=>p.id===program)?.exam_group_id;const blueprint=t.blueprints.find(b=>b.exam_group_id===group);const allocations=t.allocations.filter(a=>a.blueprint_id===blueprint?.id);const subjects=t.subjects.filter(s=>allocations.some(a=>a.subject_id===s.id));const units=t.units.filter(u=>allocations.some(a=>a.unit_id===u.id)&&(!subject||u.subject_id===subject));const topics=t.topics.filter(v=>units.some(u=>u.id===v.unit_id));
 async function start(event:React.FormEvent){event.preventDefault();setBusy(true);setError('');try{const id=await api<string>('attempts','POST',{program_id:program,mode,count,subject_id:mode==='FULL'?null:subject||null,topic_id:mode==='TOPIC'?topic||null:null,request_key:crypto.randomUUID()});router.push(`/quiz/${id}` as Route);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="grid"><form onSubmit={start} className="card form"><label>Exam program<select required value={program} onChange={e=>{setProgram(e.target.value);setSubject('');setTopic('');}}><option value="">Choose your program</option>{t.programs.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label>Practice mode<select value={mode} onChange={e=>setMode(e.target.value)}>{[['FULL','Full MEC test'],['SUBJECT','Subject practice'],['TOPIC','Topic practice'],['IMPORTANT','Important topics'],['PAST','Past questions'],['ADAPTIVE','Adaptive practice']].map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label>{mode!=='FULL'&&<><label>Subject<select required={mode==='SUBJECT'} value={subject} onChange={e=>{setSubject(e.target.value);setTopic('');}}><option value="">All available subjects</option>{subjects.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>{mode==='TOPIC'&&<label>Topic<select required value={topic} onChange={e=>setTopic(e.target.value)}><option value="">Choose a topic</option>{topics.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>}<label>Questions<input type="number" min={1} max={100} value={count} required onChange={e=>setCount(Number(e.target.value))}/></label></>}{error&&<p className="error" role="alert">{error}</p>}<button className="button" disabled={busy||!program}>{busy?'Preparing your test…':'Start test'}</button></form><section className="card"><h2>{blueprint?'Exam rules':'Choose your program'}</h2>{blueprint&&<><p>{blueprint.question_count} questions · {blueprint.duration_seconds/60} minutes</p><p>Correct: +{blueprint.marks_correct} · Incorrect: {blueprint.marks_incorrect} · Unanswered: {blueprint.marks_unanswered}</p><p>MEC qualification: {blueprint.qualification_rule.threshold}th percentile. Personal practice does not determine your MEC rank.</p><p>Cognitive mix: {Object.entries(blueprint.cognitive_distribution).map(([k,v])=>`${k.toLowerCase()} ${v}%`).join(' · ')}</p>{subjects.map(s=><div key={s.id} className="rule"><span>{s.name}</span><strong>{allocations.filter(a=>a.subject_id===s.id).reduce((n,a)=>n+a.question_count,0)}</strong></div>)}</>}<p className="muted">Tests require enough published, verified questions. If the bank cannot satisfy your selection, choose a smaller practice test.</p>{mode==='IMPORTANT'&&<p>Important-topic practice prioritizes units with greater syllabus weight.</p>}{mode==='ADAPTIVE'&&<p>Adaptive practice uses your completed answers to prioritize weak areas and adjust difficulty.</p>}</section></div>;
}
