import Link from 'next/link';
import { requirePage } from '@/lib/server/auth';
import { check,taxonomy } from '@/lib/server/data';
import { numeric,type Dashboard } from '@/lib/analytics';
import { Performance } from '@/components/performance';
export default async function Page({searchParams}:{searchParams:Promise<{admin_request?:string}>}){
 const adminRequest=(await searchParams).admin_request;
 const {db}=await requirePage();const [result,tax]=await Promise.all([db.rpc('get_dashboard'),taxonomy()]);const d=check(result) as Dashboard;
 return <>{adminRequest&&<section className="card section" role="status"><h2>Admin access {adminRequest==='pending'?'is awaiting approval':adminRequest==='rejected'?'was not approved':'is not active'}</h2><p>{adminRequest==='pending'?'A Super Admin must approve your request before the administration area becomes available.':adminRequest==='rejected'?'Your Admin request was rejected. Your student account remains active. Contact the Super Admin if you believe this needs review.':'Register or request access as an Admin, then wait for Super Admin approval.'}</p></section>}<div className="top"><div><p className="eyebrow">Your study progress</p><h1>Dashboard</h1></div><Link href="/tests" className="button">Start practice</Link></div><section className="stats">{[['Questions answered',d.questions_attempted],['Accuracy',numeric(d.accuracy,'%')],['Tests completed',d.tests_completed],['Study streak',`${d.streak} days`],['Average score',numeric(d.average_score,'%')],['Best score',numeric(d.best_score,'%')],['Test time',`${Math.round(d.study_seconds/60)} min`],['XP',d.xp]].map(([label,value])=><div className="card" key={label}><div className="muted">{label}</div><div className="metric">{value}</div></div>)}</section>{d.tests_completed===0&&<div className="card"><h2>Your progress starts with your first test</h2><p>Choose a program and practice mode. Results will appear here after you finish.</p></div>}<section className="grid"><div className="card"><h2>Recent performance</h2><Performance trends={d.trends}/></div><div className="card"><h2>Subject performance</h2>{d.dimensions.filter(s=>s.kind==='subject').map(s=><div className="rule" key={s.value}><span>{tax.subjects.find(t=>t.id===s.value)?.name??'Subject'}</span><strong>{s.answered?numeric(100*s.correct/s.answered,'%'):'—'} · {s.answered} answered</strong></div>)}{!d.dimensions.length&&<p className="muted">No completed practice yet.</p>}</div></section><section className="card section"><h2>Target score</h2><p>{d.target_score==null?'Set your target in your profile.':`Your target is ${d.target_score} / 200. Practice scores are not an MEC percentile or qualification decision.`}</p><Link href="/profile" className="text-link">Update target</Link></section></>;
}
